<?php

namespace App\Models\Inputs\Voids;

use App\Models\Inputs\Stocks\PatternStock;
use App\Traits\SecurityTrait;
use App\Traits\VoidTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class VoidPattern extends Model {
	use SoftDeletes;
	use VoidTrait;
	use SecurityTrait;
	public $timestamps = true;
	protected $fillable = [
		'security_id',
		'void_id',
		'enabler_id',
		'disabler_id',
		'enabled_at',
		'disabled_at',
	];

	static public function createClean( array $attributes = [] ) {
		return parent::create( [
			"void_id" => $attributes['void_id']
		] ); // TODO: Change the autogenerated stub
	}


	// ************************** RELASHIONSHIP **********************************
	public function pattern_stock() {
		return $this->hasOne( PatternStock::class, 'void_tool_id' );
	}

	public function void() {
		return $this->belongsTo( Voidx::class );
	}

}


